name: build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Format with spotless
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessApply

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'Wynntils'
          commit_user_email: 'admin@wynntils.com'
          commit_message: 'chore: spotless formatting'

  build:
    needs: format
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build -x spotlessCheck --no-daemon
